#include "presenters/oplog_presenters.h"

int oplog_presenters_self_test(void)
{
    return additional_code_oplog_presenter_self_test() &&
           additional_code_description_oplog_presenter_self_test() &&
           additional_code_description_period_oplog_presenter_self_test() &&
           additional_code_type_oplog_presenter_self_test() &&
           additional_code_type_description_oplog_presenter_self_test() &&
           additional_code_type_measure_type_oplog_presenter_self_test() &&
           base_regulation_oplog_presenter_self_test() &&
           certificate_oplog_presenter_self_test() &&
           certificate_description_oplog_presenter_self_test() &&
           certificate_description_period_oplog_presenter_self_test() &&
           certificate_type_oplog_presenter_self_test() &&
           certificate_type_description_oplog_presenter_self_test() &&
           chapter_oplog_presenter_self_test() &&
           commodity_oplog_presenter_self_test() &&
           complete_abrogation_regulation_oplog_presenter_self_test() &&
           duty_expression_oplog_presenter_self_test() &&
           duty_expression_description_oplog_presenter_self_test() &&
           explicit_abrogation_regulation_oplog_presenter_self_test() &&
           export_refund_nomenclature_oplog_presenter_self_test() &&
           export_refund_nomenclature_description_oplog_presenter_self_test() &&
           export_refund_nomenclature_description_period_oplog_presenter_self_test() &&
           export_refund_nomenclature_indent_oplog_presenter_self_test() &&
           footnote_oplog_presenter_self_test() &&
           footnote_association_additional_code_oplog_presenter_self_test() &&
           footnote_association_ern_oplog_presenter_self_test() &&
           footnote_association_goods_nomenclature_oplog_presenter_self_test() &&
           footnote_association_measure_oplog_presenter_self_test() &&
           footnote_association_meursing_heading_oplog_presenter_self_test() &&
           footnote_description_oplog_presenter_self_test() &&
           footnote_description_period_oplog_presenter_self_test() &&
           footnote_type_oplog_presenter_self_test() &&
           footnote_type_description_oplog_presenter_self_test() &&
           fts_regulation_action_oplog_presenter_self_test() &&
           full_temporary_stop_regulation_oplog_presenter_self_test() &&
           geographical_area_oplog_presenter_self_test() &&
           geographical_area_description_oplog_presenter_self_test() &&
           geographical_area_description_period_oplog_presenter_self_test() &&
           geographical_area_membership_oplog_presenter_self_test() &&
           goods_nomenclature_oplog_presenter_self_test() &&
           goods_nomenclature_description_oplog_presenter_self_test() &&
           goods_nomenclature_description_period_oplog_presenter_self_test() &&
           goods_nomenclature_group_oplog_presenter_self_test() &&
           goods_nomenclature_group_description_oplog_presenter_self_test() &&
           goods_nomenclature_indent_oplog_presenter_self_test() &&
           goods_nomenclature_origin_oplog_presenter_self_test() &&
           goods_nomenclature_successor_oplog_presenter_self_test() &&
           heading_oplog_presenter_self_test() &&
           language_oplog_presenter_self_test() &&
           language_description_oplog_presenter_self_test() &&
           measure_oplog_presenter_self_test() &&
           measure_action_oplog_presenter_self_test() &&
           measure_action_description_oplog_presenter_self_test() &&
           measure_component_oplog_presenter_self_test() &&
           measure_condition_oplog_presenter_self_test() &&
           measure_condition_code_oplog_presenter_self_test() &&
           measure_condition_code_description_oplog_presenter_self_test() &&
           measure_condition_component_oplog_presenter_self_test() &&
           measure_excluded_geographical_area_oplog_presenter_self_test() &&
           measure_partial_temporary_stop_oplog_presenter_self_test() &&
           measure_type_oplog_presenter_self_test() &&
           measure_type_description_oplog_presenter_self_test() &&
           measure_type_series_oplog_presenter_self_test() &&
           measure_type_series_description_oplog_presenter_self_test() &&
           measurement_oplog_presenter_self_test() &&
           measurement_unit_oplog_presenter_self_test() &&
           measurement_unit_description_oplog_presenter_self_test() &&
           measurement_unit_qualifier_oplog_presenter_self_test() &&
           measurement_unit_qualifier_description_oplog_presenter_self_test() &&
           meursing_additional_code_oplog_presenter_self_test() &&
           meursing_heading_oplog_presenter_self_test() &&
           meursing_heading_text_oplog_presenter_self_test() &&
           meursing_subheading_oplog_presenter_self_test() &&
           meursing_table_cell_component_oplog_presenter_self_test() &&
           meursing_table_plan_oplog_presenter_self_test() &&
           modification_regulation_oplog_presenter_self_test() &&
           monetary_exchange_period_oplog_presenter_self_test() &&
           monetary_exchange_rate_oplog_presenter_self_test() &&
           monetary_unit_oplog_presenter_self_test() &&
           monetary_unit_description_oplog_presenter_self_test() &&
           nomenclature_group_membership_oplog_presenter_self_test() &&
           prorogation_regulation_oplog_presenter_self_test() &&
           prorogation_regulation_action_oplog_presenter_self_test() &&
           publication_sigle_oplog_presenter_self_test() &&
           quota_association_oplog_presenter_self_test() &&
           quota_balance_event_oplog_presenter_self_test() &&
           quota_blocking_period_oplog_presenter_self_test() &&
           quota_closed_and_transferred_event_oplog_presenter_self_test() &&
           quota_critical_event_oplog_presenter_self_test() &&
           quota_definition_oplog_presenter_self_test() &&
           quota_exhaustion_event_oplog_presenter_self_test() &&
           quota_order_number_oplog_presenter_self_test() &&
           quota_order_number_origin_oplog_presenter_self_test() &&
           quota_order_number_origin_exclusion_oplog_presenter_self_test() &&
           quota_reopening_event_oplog_presenter_self_test() &&
           quota_suspension_period_oplog_presenter_self_test() &&
           quota_unblocking_event_oplog_presenter_self_test() &&
           quota_unsuspension_event_oplog_presenter_self_test() &&
           regulation_group_oplog_presenter_self_test() &&
           regulation_group_description_oplog_presenter_self_test() &&
           regulation_replacement_oplog_presenter_self_test() &&
           regulation_role_type_oplog_presenter_self_test() &&
           regulation_role_type_description_oplog_presenter_self_test() &&
           subheading_oplog_presenter_self_test() &&
           transmission_comment_oplog_presenter_self_test();
}
