#ifndef TRADE_TARIFF_C_COMMODITY_INCLUDE_PLAN_H
#define TRADE_TARIFF_C_COMMODITY_INCLUDE_PLAN_H

#include <stddef.h>
#include <stdint.h>

typedef enum {
    COMMODITY_INCLUDE_SECTION = 0,
    COMMODITY_INCLUDE_CHAPTER,
    COMMODITY_INCLUDE_CHAPTER_GUIDES,
    COMMODITY_INCLUDE_FOOTNOTES,
    COMMODITY_INCLUDE_IMPORT_TRADE_SUMMARY,
    COMMODITY_INCLUDE_HEADING,
    COMMODITY_INCLUDE_ANCESTORS,
    COMMODITY_INCLUDE_IMPORT_MEASURES,
    COMMODITY_INCLUDE_IMPORT_MEASURES_DUTY_EXPRESSION,
    COMMODITY_INCLUDE_IMPORT_MEASURES_MEASURE_TYPE,
    COMMODITY_INCLUDE_IMPORT_MEASURES_LEGAL_ACTS,
    COMMODITY_INCLUDE_IMPORT_MEASURES_SUSPENDING_REGULATION,
    COMMODITY_INCLUDE_IMPORT_MEASURES_MEASURE_CONDITIONS,
    COMMODITY_INCLUDE_IMPORT_MEASURES_MEASURE_CONDITIONS_MEASURE_CONDITION_CODE,
    COMMODITY_INCLUDE_IMPORT_MEASURES_MEASURE_CONDITION_PERMUTATION_GROUPS,
    COMMODITY_INCLUDE_IMPORT_MEASURES_MEASURE_CONDITION_PERMUTATION_GROUPS_PERMUTATIONS,
    COMMODITY_INCLUDE_IMPORT_MEASURES_MEASURE_CONDITIONS_MEASURE_CONDITION_COMPONENTS,
    COMMODITY_INCLUDE_IMPORT_MEASURES_MEASURE_COMPONENTS,
    COMMODITY_INCLUDE_IMPORT_MEASURES_MEASURE_COMPONENTS_MEASUREMENT_UNIT,
    COMMODITY_INCLUDE_IMPORT_MEASURES_MEASURE_COMPONENTS_MEASUREMENT_UNIT_QUALIFIER,
    COMMODITY_INCLUDE_IMPORT_MEASURES_RESOLVED_MEASURE_COMPONENTS,
    COMMODITY_INCLUDE_IMPORT_MEASURES_RESOLVED_MEASURE_COMPONENTS_MEASUREMENT_UNIT,
    COMMODITY_INCLUDE_IMPORT_MEASURES_GEOGRAPHICAL_AREA,
    COMMODITY_INCLUDE_IMPORT_MEASURES_GEOGRAPHICAL_AREA_CONTAINED_GEOGRAPHICAL_AREAS,
    COMMODITY_INCLUDE_IMPORT_MEASURES_EXCLUDED_GEOGRAPHICAL_AREAS,
    COMMODITY_INCLUDE_IMPORT_MEASURES_FOOTNOTES,
    COMMODITY_INCLUDE_IMPORT_MEASURES_ADDITIONAL_CODE,
    COMMODITY_INCLUDE_IMPORT_MEASURES_ORDER_NUMBER,
    COMMODITY_INCLUDE_IMPORT_MEASURES_ORDER_NUMBER_DEFINITION,
    COMMODITY_INCLUDE_IMPORT_MEASURES_ORDER_NUMBER_DEFINITION_INCOMING_QUOTA_CLOSED_AND_TRANSFERRED_EVENT,
    COMMODITY_INCLUDE_IMPORT_MEASURES_PREFERENCE_CODE,
    COMMODITY_INCLUDE_EXPORT_MEASURES,
    COMMODITY_INCLUDE_EXPORT_MEASURES_DUTY_EXPRESSION,
    COMMODITY_INCLUDE_EXPORT_MEASURES_MEASURE_TYPE,
    COMMODITY_INCLUDE_EXPORT_MEASURES_LEGAL_ACTS,
    COMMODITY_INCLUDE_EXPORT_MEASURES_SUSPENDING_REGULATION,
    COMMODITY_INCLUDE_EXPORT_MEASURES_MEASURE_CONDITIONS,
    COMMODITY_INCLUDE_EXPORT_MEASURES_MEASURE_CONDITIONS_MEASURE_CONDITION_CODE,
    COMMODITY_INCLUDE_EXPORT_MEASURES_MEASURE_CONDITION_PERMUTATION_GROUPS,
    COMMODITY_INCLUDE_EXPORT_MEASURES_MEASURE_CONDITION_PERMUTATION_GROUPS_PERMUTATIONS,
    COMMODITY_INCLUDE_EXPORT_MEASURES_MEASURE_CONDITIONS_MEASURE_CONDITION_COMPONENTS,
    COMMODITY_INCLUDE_EXPORT_MEASURES_MEASURE_COMPONENTS,
    COMMODITY_INCLUDE_EXPORT_MEASURES_MEASURE_COMPONENTS_MEASUREMENT_UNIT,
    COMMODITY_INCLUDE_EXPORT_MEASURES_MEASURE_COMPONENTS_MEASUREMENT_UNIT_QUALIFIER,
    COMMODITY_INCLUDE_EXPORT_MEASURES_RESOLVED_MEASURE_COMPONENTS,
    COMMODITY_INCLUDE_EXPORT_MEASURES_RESOLVED_MEASURE_COMPONENTS_MEASUREMENT_UNIT,
    COMMODITY_INCLUDE_EXPORT_MEASURES_GEOGRAPHICAL_AREA,
    COMMODITY_INCLUDE_EXPORT_MEASURES_GEOGRAPHICAL_AREA_CONTAINED_GEOGRAPHICAL_AREAS,
    COMMODITY_INCLUDE_EXPORT_MEASURES_EXCLUDED_GEOGRAPHICAL_AREAS,
    COMMODITY_INCLUDE_EXPORT_MEASURES_FOOTNOTES,
    COMMODITY_INCLUDE_EXPORT_MEASURES_ADDITIONAL_CODE,
    COMMODITY_INCLUDE_EXPORT_MEASURES_ORDER_NUMBER,
    COMMODITY_INCLUDE_EXPORT_MEASURES_ORDER_NUMBER_DEFINITION,
    COMMODITY_INCLUDE_COUNT
} CommodityIncludeId;

typedef struct {
    uint64_t bits;
} CommodityIncludePlan;

typedef enum {
    COMMODITY_INCLUDE_PARSE_OK = 0,
    COMMODITY_INCLUDE_PARSE_UNSUPPORTED
} CommodityIncludeParseResult;

CommodityIncludePlan commodity_include_plan_default(void);
CommodityIncludePlan commodity_include_plan_empty(void);
int commodity_include_plan_enabled(const CommodityIncludePlan *plan, CommodityIncludeId include_id);
int commodity_include_plan_enabled_any(const CommodityIncludePlan *plan,
                                       const CommodityIncludeId *include_ids,
                                       size_t include_id_count);
int commodity_include_plan_equals(const CommodityIncludePlan *left, const CommodityIncludePlan *right);
CommodityIncludeParseResult commodity_include_plan_parse(const char *include_param,
                                                         CommodityIncludePlan *out,
                                                         char *invalid_include,
                                                         size_t invalid_include_len);
const char *commodity_include_plan_path(CommodityIncludeId include_id);
int commodity_include_plan_self_test(void);

#endif
