#ifndef TRADE_TARIFF_C_ADDITIONAL_CODE_TYPE_MEASURE_TYPE_OPLOG_PRESENTER_H
#define TRADE_TARIFF_C_ADDITIONAL_CODE_TYPE_MEASURE_TYPE_OPLOG_PRESENTER_H

#include "models/oplog/additional_code_type_measure_type_model.h"

const char *additional_code_type_measure_type_oplog_presenter_resource_type(void);
const char *additional_code_type_measure_type_oplog_presenter_id(const AdditionalCodeTypeMeasureTypeOplogModel *model);
int additional_code_type_measure_type_oplog_presenter_self_test(void);

#endif
