#ifndef TRADE_TARIFF_C_CERTIFICATE_DESCRIPTION_PERIOD_OPLOG_PRESENTER_H
#define TRADE_TARIFF_C_CERTIFICATE_DESCRIPTION_PERIOD_OPLOG_PRESENTER_H

#include "models/oplog/certificate_description_period_model.h"

const char *certificate_description_period_oplog_presenter_resource_type(void);
const char *certificate_description_period_oplog_presenter_id(const CertificateDescriptionPeriodOplogModel *model);
int certificate_description_period_oplog_presenter_self_test(void);

#endif
