#ifndef TRADE_TARIFF_C_FOOTNOTE_ASSOCIATION_GOODS_NOMENCLATURE_OPLOG_PRESENTER_H
#define TRADE_TARIFF_C_FOOTNOTE_ASSOCIATION_GOODS_NOMENCLATURE_OPLOG_PRESENTER_H

#include "models/oplog/footnote_association_goods_nomenclature_model.h"

const char *footnote_association_goods_nomenclature_oplog_presenter_resource_type(void);
const char *footnote_association_goods_nomenclature_oplog_presenter_id(const FootnoteAssociationGoodsNomenclatureOplogModel *model);
int footnote_association_goods_nomenclature_oplog_presenter_self_test(void);

#endif
