#ifndef TRADE_TARIFF_C_FOOTNOTE_DESCRIPTION_PERIOD_OPLOG_PRESENTER_H
#define TRADE_TARIFF_C_FOOTNOTE_DESCRIPTION_PERIOD_OPLOG_PRESENTER_H

#include "models/oplog/footnote_description_period_model.h"

const char *footnote_description_period_oplog_presenter_resource_type(void);
const char *footnote_description_period_oplog_presenter_id(const FootnoteDescriptionPeriodOplogModel *model);
int footnote_description_period_oplog_presenter_self_test(void);

#endif
