#ifndef TRADE_TARIFF_C_FOOTNOTE_ASSOCIATION_ERN_OPLOG_PRESENTER_H
#define TRADE_TARIFF_C_FOOTNOTE_ASSOCIATION_ERN_OPLOG_PRESENTER_H

#include "models/oplog/footnote_association_ern_model.h"

const char *footnote_association_ern_oplog_presenter_resource_type(void);
const char *footnote_association_ern_oplog_presenter_id(const FootnoteAssociationErnOplogModel *model);
int footnote_association_ern_oplog_presenter_self_test(void);

#endif
