#ifndef TRADE_TARIFF_C_FOOTNOTE_ASSOCIATION_MEURSING_HEADING_OPLOG_PRESENTER_H
#define TRADE_TARIFF_C_FOOTNOTE_ASSOCIATION_MEURSING_HEADING_OPLOG_PRESENTER_H

#include "models/oplog/footnote_association_meursing_heading_model.h"

const char *footnote_association_meursing_heading_oplog_presenter_resource_type(void);
const char *footnote_association_meursing_heading_oplog_presenter_id(const FootnoteAssociationMeursingHeadingOplogModel *model);
int footnote_association_meursing_heading_oplog_presenter_self_test(void);

#endif
