#ifndef TRADE_TARIFF_C_FOOTNOTE_TYPE_DESCRIPTION_OPLOG_PRESENTER_H
#define TRADE_TARIFF_C_FOOTNOTE_TYPE_DESCRIPTION_OPLOG_PRESENTER_H

#include "models/oplog/footnote_type_description_model.h"

const char *footnote_type_description_oplog_presenter_resource_type(void);
const char *footnote_type_description_oplog_presenter_id(const FootnoteTypeDescriptionOplogModel *model);
int footnote_type_description_oplog_presenter_self_test(void);

#endif
