#ifndef TRADE_TARIFF_C_GEOGRAPHICAL_AREA_DESCRIPTION_PERIOD_OPLOG_PRESENTER_H
#define TRADE_TARIFF_C_GEOGRAPHICAL_AREA_DESCRIPTION_PERIOD_OPLOG_PRESENTER_H

#include "models/oplog/geographical_area_description_period_model.h"

const char *geographical_area_description_period_oplog_presenter_resource_type(void);
const char *geographical_area_description_period_oplog_presenter_id(const GeographicalAreaDescriptionPeriodOplogModel *model);
int geographical_area_description_period_oplog_presenter_self_test(void);

#endif
