#ifndef TRADE_TARIFF_C_LANGUAGE_DESCRIPTION_OPLOG_PRESENTER_H
#define TRADE_TARIFF_C_LANGUAGE_DESCRIPTION_OPLOG_PRESENTER_H

#include "models/oplog/language_description_model.h"

const char *language_description_oplog_presenter_resource_type(void);
const char *language_description_oplog_presenter_id(const LanguageDescriptionOplogModel *model);
int language_description_oplog_presenter_self_test(void);

#endif
