#ifndef TRADE_TARIFF_C_MEASURE_ACTION_DESCRIPTION_OPLOG_PRESENTER_H
#define TRADE_TARIFF_C_MEASURE_ACTION_DESCRIPTION_OPLOG_PRESENTER_H

#include "models/oplog/measure_action_description_model.h"

const char *measure_action_description_oplog_presenter_resource_type(void);
const char *measure_action_description_oplog_presenter_id(const MeasureActionDescriptionOplogModel *model);
int measure_action_description_oplog_presenter_self_test(void);

#endif
