#ifndef TRADE_TARIFF_C_MEASURE_CONDITION_CODE_DESCRIPTION_OPLOG_PRESENTER_H
#define TRADE_TARIFF_C_MEASURE_CONDITION_CODE_DESCRIPTION_OPLOG_PRESENTER_H

#include "models/oplog/measure_condition_code_description_model.h"

const char *measure_condition_code_description_oplog_presenter_resource_type(void);
const char *measure_condition_code_description_oplog_presenter_id(const MeasureConditionCodeDescriptionOplogModel *model);
int measure_condition_code_description_oplog_presenter_self_test(void);

#endif
