#ifndef TRADE_TARIFF_C_MEASUREMENT_UNIT_DESCRIPTION_OPLOG_PRESENTER_H
#define TRADE_TARIFF_C_MEASUREMENT_UNIT_DESCRIPTION_OPLOG_PRESENTER_H

#include "models/oplog/measurement_unit_description_model.h"

const char *measurement_unit_description_oplog_presenter_resource_type(void);
const char *measurement_unit_description_oplog_presenter_id(const MeasurementUnitDescriptionOplogModel *model);
int measurement_unit_description_oplog_presenter_self_test(void);

#endif
