#ifndef TRADE_TARIFF_C_MEASURE_TYPE_SERIES_DESCRIPTION_OPLOG_PRESENTER_H
#define TRADE_TARIFF_C_MEASURE_TYPE_SERIES_DESCRIPTION_OPLOG_PRESENTER_H

#include "models/oplog/measure_type_series_description_model.h"

const char *measure_type_series_description_oplog_presenter_resource_type(void);
const char *measure_type_series_description_oplog_presenter_id(const MeasureTypeSeriesDescriptionOplogModel *model);
int measure_type_series_description_oplog_presenter_self_test(void);

#endif
