#ifndef TRADE_TARIFF_C_MEURSING_ADDITIONAL_CODE_OPLOG_PRESENTER_H
#define TRADE_TARIFF_C_MEURSING_ADDITIONAL_CODE_OPLOG_PRESENTER_H

#include "models/oplog/meursing_additional_code_model.h"

const char *meursing_additional_code_oplog_presenter_resource_type(void);
const char *meursing_additional_code_oplog_presenter_id(const MeursingAdditionalCodeOplogModel *model);
int meursing_additional_code_oplog_presenter_self_test(void);

#endif
