#ifndef TRADE_TARIFF_C_MONETARY_UNIT_DESCRIPTION_OPLOG_PRESENTER_H
#define TRADE_TARIFF_C_MONETARY_UNIT_DESCRIPTION_OPLOG_PRESENTER_H

#include "models/oplog/monetary_unit_description_model.h"

const char *monetary_unit_description_oplog_presenter_resource_type(void);
const char *monetary_unit_description_oplog_presenter_id(const MonetaryUnitDescriptionOplogModel *model);
int monetary_unit_description_oplog_presenter_self_test(void);

#endif
