#ifndef TRADE_TARIFF_C_QUOTA_SUSPENSION_PERIOD_OPLOG_PRESENTER_H
#define TRADE_TARIFF_C_QUOTA_SUSPENSION_PERIOD_OPLOG_PRESENTER_H

#include "models/oplog/quota_suspension_period_model.h"

const char *quota_suspension_period_oplog_presenter_resource_type(void);
const char *quota_suspension_period_oplog_presenter_id(const QuotaSuspensionPeriodOplogModel *model);
int quota_suspension_period_oplog_presenter_self_test(void);

#endif
